shafishlabs/llmchain-rs

.cargo/audit.toml
=> fix: ignore cargo audit

.github/PULL_REQUEST_TEMPLATE.md, README.md
=> doc: add PR template

.github/workflows/ci.yaml, Cargo.toml, llmchain/llms/Cargo.toml, llmchain/llms/src/lib.rs, llmchain/llms/src/llm.rs, llmchain/llms/src/openai/config.rs, llmchain/llms/src/openai/mod.rs, llmchain/llms/src/openai/openai.rs, llmchain/llms/tests/it/main.rs, llmchain/llms/tests/it/openai/config.rs, llmchain/llms/tests/it/openai/mod.rs, llmchain/llms/tests/it/openai/openai.rs
* add LLMs crate
Closes #issue
=> feat: add LLMs openai

llmchain/llms/src/llm.rs, llmchain/llms/src/openai/openai.rs, llmchain/llms/tests/it/openai/openai.rs
* add usage to llm results
Closes #issue
=> chore: refactor the llm result

llmchain/loaders/src/directory/directory_loader.rs, llmchain/loaders/src/disk/disk.rs, llmchain/loaders/src/disk/local_disk.rs, llmchain/loaders/src/disk/mod.rs, llmchain/loaders/src/markdown/markdown_loader.rs, llmchain/loaders/src/text/text_loader.rs, llmchain/loaders/tests/it/directory/directory_loader.rs, llmchain/loaders/tests/it/directory/directory_splitter.rs, llmchain/loaders/tests/it/main.rs, llmchain/loaders/tests/it/markdown/markdown_loader.rs, llmchain/loaders/tests/it/markdown/markdown_splitter.rs, llmchain/loaders/tests/it/text/text_loader.rs, llmchain/loaders/tests/it/text/text_splitter.rs, llmchain/loaders/tests/testdata/directory/directory_loader.golden, llmchain/loaders/tests/testdata/directory/directory_splitter_chunk_100.golden, llmchain/loaders/tests/testdata/markdown/copy_md_loader.golden, llmchain/loaders/tests/testdata/markdown/copy_md_splitter_chunk_100.golden, llmchain/loaders/tests/testdata/markdown/copy_md_splitter_default.golden, llmchain/loaders/tests/testdata/text/example_txt_loader.golden, llmchain/loaders/tests/testdata/text/example_txt_splitter_chunk_10.golden, llmchain/loaders/tests/testdata/text/example_txt_splitter_default.golden
* add Disk interface
Closes #issue
=> feat: add Disk interface

llmchain/loaders/src/disk/local_disk.rs, llmchain/loaders/src/disk/remote_disk.rs, llmchain/loaders/src/lib.rs
* only for demo, not impl yet
Closes #issue
=> feat: add RemoteDisk impl demo

Cargo.toml, llmchain/embeddings/Cargo.toml, llmchain/embeddings/src/embedding.rs, llmchain/embeddings/src/lib.rs, llmchain/embeddings/src/openai/mod.rs, llmchain/embeddings/src/openai/openai.rs, llmchain/embeddings/tests/it/main.rs, llmchain/embeddings/tests/it/openai/mod.rs, llmchain/embeddings/tests/it/openai/openai.rs, llmchain/llms/tests/it/openai/openai.rs
=> faet: embeddings

Cargo.toml, examples/Cargo.toml, examples/src/example_embedding.rs, examples/src/example_markdown_loader.rs, examples/src/example_vector_store.rs, examples/testdata/markdowns/copy.md, examples/testdata/markdowns/subdir/42-data-type-map.md
=> feat: add examples

Cargo.toml, examples/Cargo.toml, examples/src/example_embedding.rs, examples/src/example_markdown_loader.rs, examples/src/example_vector_store.rs, llmchain/embeddings/Cargo.toml, llmchain/llms/Cargo.toml, llmchain/loaders/Cargo.toml, llmchain/vector_stores/Cargo.toml
=> feat: add logger

Cargo.toml, examples/Cargo.toml, examples/src/example_prompt_template.rs, llmchain/prompts/Cargo.toml, llmchain/prompts/src/lib.rs, llmchain/prompts/src/prompt.rs, llmchain/prompts/src/text_to_sql_prompt.rs, llmchain/prompts/tests/it/main.rs, llmchain/prompts/tests/it/prompt_template.rs, llmchain/prompts/tests/it/text_to_sql_prompt.rs, llmchain/prompts/tests/testdata/prompt_template.golden, llmchain/prompts/tests/testdata/text_to_sql_prompt.golden, llmchain/test_kits/Cargo.toml, llmchain/test_kits/src/kit.rs, llmchain/test_kits/src/lib.rs
=> feat: add prompts template

examples/Cargo.toml, examples/src/example_document_qa.rs, llmchain/llms/src/llm.rs, llmchain/vector_stores/src/databend/databend.rs, llmchain/vector_stores/src/lib.rs
=> feat: add documentation question and answering example

llmchain/llms/Cargo.toml, llmchain/llms/src/azure_openai/azure_openai.rs, llmchain/llms/src/azure_openai/mod.rs, llmchain/llms/src/lib.rs, llmchain/llms/tests/it/azure_openai/azure_openai.rs, llmchain/llms/tests/it/azure_openai/mod.rs
* add azure openai service
Closes #28
=> feat: azure openai service

examples/src/example_document_qa.rs, examples/src/example_embedding.rs, examples/src/example_vector_store.rs, llmchain/embeddings/src/databend/databend.rs, llmchain/embeddings/src/databend/mod.rs, llmchain/embeddings/src/lib.rs, llmchain/embeddings/tests/it/databend/databend.rs, llmchain/embeddings/tests/it/databend/mod.rs, llmchain/llms/tests/it/azure_openai/azure_openai.rs
* add databend embedding
Closes #issue
=> feat: databend embedding

examples/src/example_document_qa.rs, examples/src/example_markdown_loader.rs, llmchain/loaders/src/directory/directory_loader.rs, llmchain/loaders/src/document.rs, llmchain/loaders/src/document_path.rs, llmchain/loaders/src/lib.rs, llmchain/loaders/src/markdown/markdown_loader.rs, llmchain/loaders/src/text/text_loader.rs, llmchain/loaders/tests/it/directory/directory_loader.rs, llmchain/loaders/tests/it/directory/directory_splitter.rs, llmchain/loaders/tests/it/markdown/markdown_loader.rs, llmchain/loaders/tests/it/markdown/markdown_splitter.rs, llmchain/loaders/tests/it/text/text_loader.rs, llmchain/loaders/tests/it/text/text_splitter.rs
* make document path more polymorphic
Closes #issue
=> feat: add document path to accept string/range

examples/Cargo.toml, examples/src/example_document_qa.rs, examples/src/example_github_inspect.rs, examples/src/example_markdown_loader.rs, llmchain/llms/Cargo.toml, llmchain/llms/src/databend/databend.rs, llmchain/loaders/Cargo.toml, llmchain/loaders/src/directory/directory_loader.rs, llmchain/loaders/src/document.rs, llmchain/loaders/src/document_path.rs, llmchain/loaders/src/github/github_pr_loader.rs, llmchain/loaders/src/github/github_pr_splitter.rs, llmchain/loaders/src/github/mod.rs, llmchain/loaders/src/markdown/markdown_loader.rs, llmchain/loaders/src/text/text_loader.rs, llmchain/loaders/tests/it/directory/directory_loader.rs, llmchain/loaders/tests/it/directory/directory_splitter.rs, llmchain/loaders/tests/it/github/github_pr_loader.rs, llmchain/loaders/tests/it/github/github_pr_splitter.rs, llmchain/loaders/tests/it/github/mod.rs, llmchain/loaders/tests/it/main.rs, llmchain/loaders/tests/it/markdown/markdown_loader.rs, llmchain/loaders/tests/it/markdown/markdown_splitter.rs, llmchain/loaders/tests/it/text/text_loader.rs, llmchain/loaders/tests/it/text/text_splitter.rs, llmchain/loaders/tests/testdata/github/github_pr_loader.golden, llmchain/loaders/tests/testdata/github/github_pr_splitter_default.golden, llmchain/vector_stores/src/databend/databend.rs
```
EXPORT GITHUB_TOKEN=<your-personal-github-token>
EXPORT DATABEND_DSN=<your-databend-dsn>
cargo run --bin example_github_inspect
```
Closes #34
=> feat: github pr loader

examples/src/example_document_qa.rs, examples/src/example_github_inspect.rs
=> fix: fix path and content

llmchain/loaders/Cargo.toml, llmchain/loaders/src/pdf/mod.rs, llmchain/loaders/src/pdf/pdf_loader.rs
This PR add PDF loader for llmchain.
Closes https://github.com/shafishlabs/llmchain.rs/issues/6
=> feat: Add PDF Loader

Cargo.toml, export/Cargo.toml, export/src/lib.rs, llmchain/llms/Cargo.toml, llmchain/vector_stores/Cargo.toml
=> feat: add export

llmchain/llms/src/databend/databend.rs, llmchain/vector_stores/Cargo.toml, llmchain/vector_stores/src/databend/databend.rs
=> add more log

examples/src/example_github_pr_summary.rs, llmchain/memory/Cargo.toml, llmchain/memory/src/github_pr_summary.rs, llmchain/memory/src/lib.rs, llmchain/memory/src/summary.rs
=> chore: improve the github pr summary

examples/src/example_github_pr_summary.rs, llmchain/loaders/src/github/github_pr_splitter.rs, llmchain/loaders/tests/testdata/github/github_pr_splitter_default.golden, llmchain/memory/src/github_pr_summary.rs, llmchain/prompts/src/github_pr_summary_prompt.rs
=> feat: improve github pr

llmchain/memory/src/github_pr_summary.rs, llmchain/prompts/src/github_pr_summary_prompt.rs
=> feat: improve the prompt for the github pr

llmchain/prompts/src/github_pr_summary_prompt.rs, rust-toolchain.toml
=> feat: improve git pr prompt

Cargo.toml, examples/src/example_github_pr_summary.rs, llmchain/common/Cargo.toml, llmchain/common/tests/it/token.rs, llmchain/loaders/src/github/github_pr_loader.rs, llmchain/memory/src/github_pr_summary.rs, llmchain/prompts/src/github_pr_summary_prompt.rs
* **Improved Summary Format** Added a new line to the final summary format to include a summary generated by llmchain.rs and changed the format to include the number of tokens in the summary.
* **Imported Function** Imported the chat_tokens function from llmchain_common.
* **Changed Prompt Template** Changed the prompt template to ask for a summarized text bullet list of all code changes in the diff grouped by file, removed unnecessary text, and changed the format of the final summary to remove the "====" separator. Added the number of tokens in the prompt and final summary to the log output.
* **Updated Prompt Guidelines** Changed the prompt template to ask for a clear and concise summary of the main changes made in a pull request and added guidelines for summarizing the changes. Changed …
=> feat: make github pr better

llmchain/loaders/Cargo.toml
=> chore: futures = futures = 0.3.*

Cargo.toml, llmchain/llms/Cargo.toml, llmchain/llms/src/azure_openai/azure_openai.rs, llmchain/llms/src/openai/openai.rs
=> chore: upgrade async-openai

llmchain/common/tests/it/token.rs, llmchain/memory/src/github_pr_summary.rs, llmchain/prompts/src/github_pr_summary_prompt.rs
* **Updated Pull Request Summary Guidelines**
The guidelines for summarizing code changes in a pull request have been updated. Changes include classifying all changelogs into 1 to 5 points and providing a concise summary for each point within 50 words.
* **Added Template for Pull Request Summaries**
A template has been added to the memory/src/github_pr_summary.rs file for summarizing code changes in a pull request. The template includes guidelines for grouping changes by file and using bullet points to describe them.
Overall, these changes aim to improve the clarity and organization of pull request summaries, making it easier for developers to understand and review code changes.
=> chore: improve github pr summary

.github/workflows/ci.yaml, llmchain/loaders/tests/it/github/github_pr_loader.rs, llmchain/loaders/tests/it/github/github_pr_splitter.rs
=> chore: fix ut

examples/Cargo.toml, examples/src/example_document_qa.rs, examples/src/example_embedding.rs, examples/src/example_github_pr_summary.rs, examples/src/example_github_repo_loader.rs, examples/src/example_markdown_loader.rs, examples/src/example_prompt_template.rs, examples/src/example_vector_store.rs, export/Cargo.toml, export/src/lib.rs, llmchain/test_kits/src/lib.rs, llmchain/test_kits/src/repl.rs
=> chore: change to export llmchain for examples

README.md, llmchain/Cargo.toml, llmchain/README.md
=> bump version to 0.1.2

README.md
=> ln README.md to llmchain/README.md

.github/workflows/ci.yaml, examples/Cargo.toml, llmchain/Cargo.toml, llmchain/src/llms/databend/databend.rs, llmchain/src/vector_stores/databend/databend.rs
=> fix: update usage for databend driver

llmchain/src/loaders/markdown/markdown_splitter.rs, llmchain/tests/it/loaders/markdown/markdown_splitter.rs, llmchain/tests/testdata/loaders/markdown/copy-hyphen.md, llmchain/tests/testdata/loaders/markdown/copy_md_splitter_custom_separator.golden
extend MarkdownSplitter for custom separator 
Closes #issue
fix #70
=> feat: support DocumentSplitter support custom separators

llmchain/src/embeddings/openai/openai.rs, llmchain/tests/it/embeddings/openai/openai.rs
Do note that this is a breaking change. If you would like to not have breaking changes let me know the name of the function.
=> pass OpenAI to OpenAIEmbedding to allow setting base url
